{
  "formatVersion": "1.1",
  "component": {
    "group": "com.posthog",
    "module": "posthog-android",
    "version": "3.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.posthog",
          "module": "posthog",
          "version": {
            "requires": "3.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "posthog-android-3.5.1.aar",
          "url": "posthog-android-3.5.1.aar",
          "size": 87354,
          "sha512": "f8cf7b711d850a0002af46753bf571196299d8c41a8c66865c60bd3b797ce01bb7d29346dfbfaafbcda3e0f6919b16e9fd1dc08c06e56a392cd379d0c29d8fc7",
          "sha256": "2e78ff8d809cb409009198f6529cc3ca5b49ae7d3a47db005745b1e2bd04f43b",
          "sha1": "e0b9ebd2181bd6a197df18ea618434a00f01971f",
          "md5": "767085b094c566f4bb0013e23534f8b1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.curtains",
          "module": "curtains",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "com.posthog",
          "module": "posthog",
          "version": {
            "requires": "3.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "posthog-android-3.5.1.aar",
          "url": "posthog-android-3.5.1.aar",
          "size": 87354,
          "sha512": "f8cf7b711d850a0002af46753bf571196299d8c41a8c66865c60bd3b797ce01bb7d29346dfbfaafbcda3e0f6919b16e9fd1dc08c06e56a392cd379d0c29d8fc7",
          "sha256": "2e78ff8d809cb409009198f6529cc3ca5b49ae7d3a47db005745b1e2bd04f43b",
          "sha1": "e0b9ebd2181bd6a197df18ea618434a00f01971f",
          "md5": "767085b094c566f4bb0013e23534f8b1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "posthog-android-3.5.1-sources.jar",
          "url": "posthog-android-3.5.1-sources.jar",
          "size": 29591,
          "sha512": "36d1b32e88bbe043f868b48c008cd18e40b77bc1f45c4e587f86bcdb6140fabf2c615bd744369992d75d7ab9ea1f5d746f32b8923cb356423fdc1557bf4f97c6",
          "sha256": "777254fb5e08161347d708f2dcb1645cc34b50d64c65f6c22eec716d355e511c",
          "sha1": "135069bf84692890c1d4d2cfdfac0979135d3144",
          "md5": "b744213d8bcf6becc0e29bd957ba9e03"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "posthog-android-3.5.1-javadoc.jar",
          "url": "posthog-android-3.5.1-javadoc.jar",
          "size": 319271,
          "sha512": "f0db31d797e973ba323a81c6c2b4f2a2923b0119f0c4802a32a98c4e9e2ca616114e159c03282db5261813f012f55c8228ca0952a20db258b90f4185ae72141b",
          "sha256": "a8e8f781cbc2ed738226965482b0a17a8e7fbc266324961f09512cb0a4e01173",
          "sha1": "6c00411df6aaaafc47df194e445a68cd622e79d3",
          "md5": "aa7b1c4bed994f6281d89c4b458f7e88"
        }
      ]
    }
  ]
}
